Test vcpkg json, following MS documentation
Followed this dev blog:
https://devblogs.microsoft.com/cppblog/registries-bring-your-own-libraries-to-vcpkg/

Got the following errors:
1)
Failed to parse configuration: D:\Dev\Perso\GitHub\dxc-hlsl-2-spirv-test\vcpkg-configuration.json
    $.registries[0] (a git registry): missing required field 'baseline' (a baseline)
2)
error: The configuration defined in D:\Dev\Perso\GitHub\dxc-hlsl-2-spirv-test\vcpkg-configuration.json is invalid.
Using registries requires that a baseline is set for the default registry or that the default registry is null.
See https://learn.microsoft.com/vcpkg/users/registries for more details.